export const CREATC_QOUTE_REQUEST = 'CREATC_QOUTE_REQUEST';
export const CREATC_QOUTE_SUCCESS = 'CREATC_QOUTE_SUCCESS';
export const CREATC_QOUTE_ERROR = 'CREATC_QOUTE_ERROR';

export const DELETE_QOUTE = 'DELETE_QOUTE';

// Auth constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILURE = 'FETCH_LIST_FAILURE';

